// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package shu

import (
	"shu/api/shu"
	meihuaLogic "shu/internal/logic/meihua"
)

type ControllerV1 struct {
	meihua *meihuaLogic.Meihua
}

func NewV1() shu.IShuV1 {
	return &ControllerV1{
		meihua: meihuaLogic.NewMeihua(),
	}
}
